version: '3.8'

services:
  # PostgreSQL with PostGIS
  postgres:
    image: postgis/postgis:17-3.5
    container_name: twigger-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: twigger
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Firebase Emulator (for local development)
  firebase-emulator:
    image: andreysenov/firebase-tools:latest
    container_name: twigger-firebase-emulator
    ports:
      - "9099:9099"  # Auth emulator
      - "4000:4000"  # Emulator UI
    environment:
      - FIREBASE_PROJECT_ID=twigger-dev
    command: firebase emulators:start --only auth --project twigger-dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9099/"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis (for caching)
  redis:
    image: redis:7-alpine
    container_name: twigger-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
  redis-data:
