// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlnVoAEG0o_EuA9OCscgWsG1aSAmpxfiY',
    appId: '1:53871324357:web:659bf3f616f152fda194ac',
    messagingSenderId: '53871324357',
    projectId: 'twigger-prod',
    authDomain: 'twigger-prod.firebaseapp.com',
    storageBucket: 'twigger-prod.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKgGqkB8HaXJv4liSpfKuDhOHDOYLM-A4',
    appId: '1:53871324357:android:84d3be44efeadbcfa194ac',
    messagingSenderId: '53871324357',
    projectId: 'twigger-prod',
    storageBucket: 'twigger-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD26oEN8xuUH6EIh9tRR6pnfFdC35gCf_0',
    appId: '1:53871324357:ios:ccbea83039e00b25a194ac',
    messagingSenderId: '53871324357',
    projectId: 'twigger-prod',
    storageBucket: 'twigger-prod.firebasestorage.app',
    iosClientId: '53871324357-ld0us2jumg5hp2gkq09kao2luil0h0ke.apps.googleusercontent.com',
    iosBundleId: 'com.twigger.frontend',
  );

}